name = "ResourceManagement"
uuid = "76c75107-e2c8-4818-8fcc-81cedefbacc5"
authors = ["Gil Junqueira"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
